version: '3.1'

services:

  csvfiledef:
    image: esurveillance/filedefinitions
    restart: always
    container_name: filedefinitions
    ports:
      - 10000:10000
    depends_on:
      - mongodb
    networks:
      - dprp
    env_file:
    - ./.env

  mongodb:
      image: mongo:latest
      container_name: "mongodb"
      env_file:
        - ./.env
      environment:
        - MONGO_DATA_DIR=/data/mde_db
        - MONGO_LOG_DIR=/dev/null
      volumes:
        - ./data/mde_db:/data/db
      ports:
        - ${MONGO_MDE_PORT}:${MONGO_MDE_PORT}
      command: mongod --port ${MONGO_MDE_PORT} --smallfiles --logpath=/dev/null # --quiet
      networks:
        - dprp
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server ~/Downloads/minio
    networks:
      - dprp


networks:
  dprp:
    driver: bridge
