server:
  servlet:
    context-path: /fileDefinition
  port: 10000
  apiContext:
  versionContext: v

spring:
  application:
    name: FILEDefinition-Service

  profiles:
    active: ${SPRING_PROFILE}


  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/file_definition
      #uri: mongodb://158.111.44.51:27018/file_definition
eip-service-config:
  pageInfo:
    maxPageSize: 100
    defaultPageSize: 20


about:
  summary: This is a stub for starting Spring REST RENAME_ME. It includes basic Boot configuration, Docker, and a About service that reads this YAML file.
  docs: http://localhost:${server.port}${server.servlet.context-path}/swagger-ui.html

  versions:
    - v1
  contacts:
    -
      name: Marcelo Caldas
      email: mcq1@cdc.gov
      role: Soft. Architect

---
spring:
  profiles: DOCKER

  data:
    mongodb:
      uri: mongodb://${MONGO_HOST}:${MONGO_PORT}/file_definitions


---
spring:
  profiles: LOCAL

  data:
    mongodb:
      uri: mongodb://localhost:27018/file_definition


---
spring:
  profiles: QA



---
spring:
  profiles: STG


---
spring:
  profiles: PROD
